/**
 * Config Sorter
 * Sorts generated config keys to match the order in sample config
 */

/**
 * Sample config structure for ordering
 * This is the reference structure that defines the key order
 */
const SAMPLE_CONFIG = {
  "title": "",
  "language": "",
  "currency": "",
  "currency_symbol": "",
  "property_status": "",
  "photos": [],
  "address": {
    "street": "",
    "city": "",
    "neighborhood": "",
    "state": "",
    "zipcode": "",
    "country": "",
    "subdivision": ""
  },
  "price_info": {
    "price": 0,
    "is_discounted": false,
    "original_price": 0,
    "price_per_unit": {
      "amount": 0,
      "unit": ""
    }
  },
  "beds": 0,
  "baths": 0,
  "property_type": "OTHER",
  "year_built": 0,
  "is_new_construction": false,
  "mls_id": "",
  "living_area": {
    "value": 0,
    "unit": ""
  },
  "lot_size": {
    "value": 0,
    "unit": ""
  },
  "highlights": [
    {
      "title": "",
      "value": "",
      "icon": ""
    }
  ],
  "description": "",
  "features_amenities": {
    "interior": {
      "floor_covering": [],
      "kitchen_features": [],
      "heating": [],
      "cooling": [],
      "fireplace": false
    },
    "appliances": [],
    "parking": {
      "type": "",
      "spaces": 0,
      "covered": false
    },
    "outdoor": {
      "amenities": [],
      "pool": false,
      "balcony_terrace": false,
      "garden": false
    },
    "building": {
      "architecture_style": "",
      "exterior_type": "",
      "elevator": false,
      "security_features": []
    },
    "energy": {
      "energy_rating": "",
      "solar": false,
      "ev_charger": false
    }
  },
  "agent": {
    "name": "",
    "agency": "",
    "phone": "",
    "email": ""
  },
  "location": {
    "latitude": 0,
    "longitude": 0
  },
  "neighborhood": {
    "schools": [],
    "lifestyle": "",
    "street_view_url": ""
  },
  "mortgage_info": {
    "interest_rate": 0,
    "property_tax": {
      "amount": 0,
      "period": "annual|monthly|unknown"
    },
    "hoa_fee": {
      "amount": 0,
      "period": "monthly|quarterly|annual|unknown"
    }
  },
  "virtual_tour_url": "",
  "floorplan_url": "",
  "font": "",
  "brand_color": "",
  "completeness": 0
}

/**
 * Sort object keys according to a reference object's key order
 * Recursively sorts nested objects as well
 */
function sortObjectKeys(obj: any, reference: any): any {
  if (!obj || typeof obj !== 'object' || Array.isArray(obj)) {
    return obj
  }

  // Get key order from reference
  const referenceKeys = Object.keys(reference || {})
  
  // Create new object with sorted keys
  const sorted: any = {}
  
  // First, add keys that exist in reference (in reference order)
  for (const key of referenceKeys) {
    if (key in obj) {
      if (typeof obj[key] === 'object' && obj[key] !== null && !Array.isArray(obj[key])) {
        // Recursively sort nested objects
        sorted[key] = sortObjectKeys(obj[key], reference[key])
      } else {
        sorted[key] = obj[key]
      }
    }
  }
  
  // Then, add any keys that don't exist in reference (at the end)
  for (const key of Object.keys(obj)) {
    if (!(key in sorted)) {
      if (typeof obj[key] === 'object' && obj[key] !== null && !Array.isArray(obj[key])) {
        sorted[key] = sortObjectKeys(obj[key], {})
      } else {
        sorted[key] = obj[key]
      }
    }
  }
  
  return sorted
}

/**
 * Sort generated config to match sample config structure
 * 
 * @param generatedConfig - The config generated by OpenAI
 * @returns Sorted config with keys in the same order as sample config
 */
export function sortConfigToSampleOrder(generatedConfig: any): any {
  try {
    return sortObjectKeys(generatedConfig, SAMPLE_CONFIG)
  } catch (error) {
    console.warn('⚠️ [Config Sorter] Failed to sort config, returning original:', error)
    return generatedConfig
  }
}
