/**
 * Config Sorter
 * Sorts generated config keys to match the order in sample config
 */

import { readFileSync } from 'fs'
import { join } from 'path'

/**
 * Get sample config structure for ordering
 */
function getSampleConfig(): any {
  const sampleConfigPath = join(process.cwd(), 'docs', 'site-config-sample.json')
  return JSON.parse(readFileSync(sampleConfigPath, 'utf-8'))
}

/**
 * Sort object keys according to a reference object's key order
 * Recursively sorts nested objects as well
 */
function sortObjectKeys(obj: any, reference: any): any {
  if (!obj || typeof obj !== 'object' || Array.isArray(obj)) {
    return obj
  }

  // Get key order from reference
  const referenceKeys = Object.keys(reference || {})
  
  // Create new object with sorted keys
  const sorted: any = {}
  
  // First, add keys that exist in reference (in reference order)
  for (const key of referenceKeys) {
    if (key in obj) {
      if (typeof obj[key] === 'object' && obj[key] !== null && !Array.isArray(obj[key])) {
        // Recursively sort nested objects
        sorted[key] = sortObjectKeys(obj[key], reference[key])
      } else {
        sorted[key] = obj[key]
      }
    }
  }
  
  // Then, add any keys that don't exist in reference (at the end)
  for (const key of Object.keys(obj)) {
    if (!(key in sorted)) {
      if (typeof obj[key] === 'object' && obj[key] !== null && !Array.isArray(obj[key])) {
        sorted[key] = sortObjectKeys(obj[key], {})
      } else {
        sorted[key] = obj[key]
      }
    }
  }
  
  return sorted
}

/**
 * Sort generated config to match sample config structure
 * 
 * @param generatedConfig - The config generated by OpenAI
 * @returns Sorted config with keys in the same order as sample config
 */
export function sortConfigToSampleOrder(generatedConfig: any): any {
  try {
    const sampleConfig = getSampleConfig()
    return sortObjectKeys(generatedConfig, sampleConfig)
  } catch (error) {
    console.warn('⚠️ [Config Sorter] Failed to sort config, returning original:', error)
    return generatedConfig
  }
}
